# Generated by Django 3.1 on 2022-02-11 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apprentice',
            fields=[
                ('id_app', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Debe de ingresar sus nombres completos', max_length=100, verbose_name='Nombres')),
                ('surname', models.CharField(help_text='Ingrese sus apellidos completos', max_length=200, verbose_name='Apellidos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
        ),
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id_ass', models.AutoField(primary_key=True, serialize=False)),
                ('entry_boolean', models.BooleanField(default=False)),
                ('entry_at', models.DateTimeField(auto_now_add=True, verbose_name='Hora de Ingreso')),
                ('exit_boolean', models.BooleanField(default=False)),
                ('exit_at', models.DateTimeField(auto_now=True, verbose_name='Hora de Salida')),
                ('apprentice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.apprentice', verbose_name='Aprendis')),
            ],
        ),
    ]
